---
title: "Strings and factors "
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(p8105.datasets)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)


theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colur = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Strings and regex (regular expression)

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")

#Strings are case sensitive
str_replace(string_vec, "jeff", "Jeff")

```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think") #Carrot is for beginning of line
str_detect(string_vec, "i think$") #End of line
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush") #[] for either or in string 
```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # . is a special character indicating anything else, 
#If you actually want to capture . have to use \.
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```


## Factors 

```{r}
vec_sex = factor(c("male", "male", "female", "female"))

vec_sex

as.numeric(vec_sex)
```

What happens if I relevel some of these?

```{r}
vec_sex = fct_relevel(vec_sex, "male")
```

## NSDUH

